# Generated by Django 5.1.3 on 2024-11-27 14:23

import bonnes_lectures.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonnes_lectures', '0002_author_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=bonnes_lectures.fields.IsbnField(max_length=17, unique=True),
        ),
    ]
